name: Test Database

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-database:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'  # Upravte podle verze PHP, kterou používáte
                  extensions: pdo_mysql

            - name: Start MariaDB
              uses: mirromutth/mysql-action@v1
              with:
                  mysql version: '11.0'  # Specifikujte verzi MariaDB
                  mysql database: contributte
                  mysql user: contributte
                  mysql password: contributte
                  mysql root password: contributte

            - name: Install Composer dependencies
              run: composer install

            - name: Wait for MySQL
              run: |
                  until mysqladmin ping -h 127.0.0.1 -u contributte -pcontributte --silent; do
                    sleep 1
                  done

            - name: Run database migrations
              env:
                  DATABASE_URL: "mysql:host=127.0.0.1;port=3306;dbname=contributte;user=contributte;password=contributte"
              run: php www/index.php migrations:migrate --no-interaction

            - name: Load database fixtures
              env:
                  DATABASE_URL: "mysql:host=127.0.0.1;port=3306;dbname=contributte;user=contributte;password=contributte"
              run: php www/index.php fixtures:load --no-interaction
