name: Test Database

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-database:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'  # Upravte podle verze PHP, kterou používáte
                  extensions: pdo_mysql

            - uses: getong/mariadb-action@v1.11
              with:
                  host port: 3306 # Optional, default value is 3306. The port of host
                  container port: 3306 # Optional, default value is 3306. The port of container
                  character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
                  collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
                  mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
                  mysql database: 'contributte' # Optional, default value is "test". The specified database which will be create
                  mysql root password: 'contributte' # Required if "mysql user" is empty, default is empty. The root superuser password
                  mysql user: 'contributte' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
                  mysql password: 'contributte' # Required if "mysql user" exists. The password for the "mysql user"

            - name: Install Composer dependencies
              run: composer install

            - name: Wait for MySQL
              run: |
                  until mysqladmin ping -h 127.0.0.1 -u contributte -pcontributte --silent; do
                    sleep 1
                  done

            - name: Create necessary directories
              run: |
                  mkdir -p var/log
                  mkdir -p var/cache

            - name: Run database migrations
              env:
                  DATABASE_URL: "mysql:host=127.0.0.1;port=3306;dbname=contributte;user=contributte;password=contributte"
              run: bin/console orm:schema-tool:update --force

            - name: Load database fixtures
              env:
                  DATABASE_URL: "mysql:host=127.0.0.1;port=3306;dbname=contributte;user=contributte;password=contributte"
              run: bin/console doctrine:fixtures:load --no-interaction
